### ISSUE TITLE
表格数据为空时新增的问题

### ISSUE THREAD

**Issue by wningrid** [zhaojun1998/Shiro-Action#10]
目前新增时，是在关闭新增弹窗之后，点击分页的组件的第一页来实现刷新表格的。在没有数据的时候，分页控件不展示，点不到这个按钮，没法刷新，建议使用table.reload来重载表格

**Comment by zhaojun1998** [comment]
嗯，这是个 BUG，之前之所以不用 table.reload 刷新，是因为他会闪一下，我会修复这个功能的。
