### ISSUE TITLE
登录后自动退出的问题

### ISSUE THREAD

**Issue by wningrid** [zhaojun1998/Shiro-Action#11]
部署的线上演示demo，登录后有时会自动退出，跳转到http://shiro.jun6.net/login;JSESSIONID=3fab467f-8475-4fd0-8106-a7e7bf6f21c6  这样的带个sessionid参数的链接，这个没做oath之前有，做了oath之后还是有。

我清理掉cookie问题还能重现。cookie和session storage都清理掉之后就正常了。

**Comment by zhaojun1998** [comment]
这个是 shiro 的特性，因为重定向请求没办法写 cookie，只能通过这种方式，通过 `sessionManager.setSessionIdUrlRewritingEnabled(false)` 即可关闭这个功能。
