### ISSUE TITLE
UserNameRealm是不是重复注入了

### ISSUE THREAD

**Issue by BreakSheep** [zhaojun1998/Shiro-Action#14]
Action：
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by zhaojun1998** [comment]
@BreakSheep 是最新的代码启动这样的吗，我这里没发现这个信息

**Comment by BreakSheep** [comment]
是的。我前几天拉下来。发现启动异常。看了你的代码发现UserNameRealm上边有Comonent注解。但是在ShiroConfig里边UsernameRealm方法还有个Bean注解

发自我的iPhone

**Comment by zhaojun1998** [comment]
@BreakSheep UserNameRealm 上的 `@Comonent` 注解可以去掉，但留着也不会影响功能，他也只会初始化一次，即按照 `@Bean` 中的配置初始化。
至于你说的启动异常，是指无法正常启动吗，还是有警告信息。你拉下来代码后有更改代码内容吗，比如更换依赖版本等操作。

如果可以贴出日志信息就更好了。谢谢。

**Comment by BreakSheep** [comment]
中午去再去看看。我拉下来只改了改redis和datasource配置。确认一下是不是我动了才出的问题

发自我的iPhone

**Comment by BreakSheep** [comment]
问题找到了。源码没有问题。是因为我用的mysql8.0。而Springboot2.0.6默认mysql5.1的驱动。所以我改成了2.1.x。这才导致启动报错。具体原因是在2.1.x的spring.main中加入了一个属性如图，这个属性在2.0.6中我没有找到  当我将这个属性设置为true后  项目启动不会再抛出重复注入的异常 。由于我的疏忽提出了错误的意见。十分抱歉


发自我的iPhone
