### ISSUE TITLE
本地启动服务，界面操作日志切面方法，没有生效

### ISSUE THREAD

**Issue by 991697456** [zhaojun1998/Shiro-Action#17]
本地启动服务，界面操作日志切面方法，没有生效，执行修改角色操作，dug断点并没有进入

**Comment by zhaojun1998** [comment]
配置文件中有开启记录操作日志和登录日志功能，你看下是否已开启：
```
shiro-action.log.operation = false
shiro-action.log.login = false
```

**Comment by 991697456** [comment]
thanks master !!!
                已经恢复，application-dev.properties，修改
shiro-action.log.operation = true
shiro-action.log.login = true
功能恢复

**Comment by 991697456** [comment]
Thank you very much for the open source project！！！
